fos_oauth_server:
    client_class: Jbnahan\ServerBundle\Entity\Client
    access_token_class: Jbnahan\ServerBundle\Entity\AccessToken
    refresh_token_class: Jbnahan\ServerBundle\Entity\RefreshToken
    auth_code_class: Jbnahan\ServerBundle\Entity\AuthCode
    db_driver: orm
    service:
        user_provider: platform.user.provider
        options:
            supported_scopes: user