fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

jbnahan_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: JbnahanServerBundle:Security:login }

jbnahan_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: JbnahanServerBundle:Security:loginCheck }

jbnahan_server:
    resource: "@JbnahanServerBundle/Resources/config/routing.yml"
    prefix:   /

