security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Jbnahan\ServerBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: true
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_provider:
            id: platform.user.provider
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        oauth_tocken:
            pattern: ^/oauth/v2/tocken
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                provider: user_provider
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        oauth_authorize:
            pattern: ^/oauth/v2/auth
            form_login:
                provider: user_provider
                check_path: jbnahan_oauth_server_auth_login_check
                login_path: jbnahan_oauth_server_auth_login
            anonymous: true

        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/api roles: [ IS_AUTHENTICATED_FULLY ] }

        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
