# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    League\OAuth2\Server\AuthorizationServer:
        arguments:
            - '@App\Repository\ClientRepository'
            - '@App\Repository\AccessTokenRepository'
            - '@App\Repository\ScopeRepository'
            - '%env(resolve:PRIVATE_KEY_PATH)%'
            - '%env(ENCRIPTION_KEY)%'
        calls:
            - ['enableGrantType', ['@League\OAuth2\Server\Grant\AuthCodeGrant', '@interval_1h']]

    League\OAuth2\Server\Grant\AuthCodeGrant:
        arguments:
            - '@App\Repository\AuthCodeRepository'
            - '@App\Repository\RefreshTokenRepository'
            - '@interval_10m'
        calls:
            - ['setRefreshTokenTTL', ['@interval_1m']]
    interval_10m:
        class: DateInterval
        arguments: ['PT10M']
    interval_1h:
        class: DateInterval
        arguments: ['PT1H']
    interval_1m:
        class: DateInterval
        arguments: ['P1M']

    Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface: '@Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory'
    Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory: ~

    Nyholm\Psr7\Factory\Psr17Factory: ~
    Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory:
        arguments:
            - '@Nyholm\Psr7\Factory\Psr17Factory'
            - '@Nyholm\Psr7\Factory\Psr17Factory'
            - '@Nyholm\Psr7\Factory\Psr17Factory'
            - '@Nyholm\Psr7\Factory\Psr17Factory'

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface: '@Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory'
