Jbnahan\ServerBundle\Entity\RefreshToken:
    type: entity
    table: null
    repositoryClass: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: Client
        user:
            targetEntity: User

    lifecycleCallbacks: {  }

