Jbnahan\ServerBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Jbnahan\ServerBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '25'
            unique: true
        email:
            type: string
            length: 255
            unique: true
        salt:
            type: string
            length: '32'
        password:
            type: string
            length: '40'
        isActive:
            type: boolean
            column: is_active
    lifecycleCallbacks: {  }
