parameters:
#    jbnahan_server.example.class: Jbnahan\ServerBundle\Example
    platform.entity.user.class: Jbnahan\ServerBundle\Entity\User

services:
#    jbnahan_server.example:
#        class: %jbnahan_server.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    platform.user.manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManagerForClass
        arguments: [%platform.entity.user.class%]

    platform.user.repository:
        class: Jbnahan\ServerBundle\Repository\UserRepository
        factory_service: platform.user.manager
        factory_method: getRepository
        arguments: [%platform.entity.user.class%]

    platform.user.provider:
        class: Jbnahan\ServerBundle\Provider\UserProvider
        arguments: [@platform.user.repository]